// angular-client/src/app/components/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {
  navigation = [
    { name: 'Home', href: '/' },
    { name: 'Movies', href: '/movies' },
    { name: 'TV Shows', href: '/tv-shows' },
    { name: 'My List', href: '/my-list' }
  ];
  isSearchOpen = false;
  isMobileMenuOpen = false;
}

<header class="fixed top-0 left-0 right-0 z-50 bg-background/95 backdrop-blur-sm border-b border-border/40">
  <div class="container">
    <div style="display:flex;align-items:center;justify-content:space-between;padding:12px 0;">
      <a href="/" class="logo" style="font-weight:700;font-size:20px;color:#60a5fa;">WatchID</a>

      <nav class="desktop-nav" style="display:none;">
        <!-- basic desktop nav — expand as needed -->
        <a *ngFor="let item of navigation" href="{{item.href}}" style="margin-left:18px">{{item.name}}</a>
      </nav>

      <div class="actions" style="display:flex;gap:8px;align-items:center;">
        <button (click)="isSearchOpen = !isSearchOpen">Search</button>
        <button (click)="isMobileMenuOpen = !isMobileMenuOpen" class="mobile-menu">Menu</button>
      </div>
    </div>

    <div *ngIf="isMobileMenuOpen" style="padding-bottom:12px;">
      <div style="display:flex;flex-direction:column;gap:8px;padding-top:8px;">
        <a *ngFor="let item of navigation" href="{{item.href}}">{{item.name}}</a>
      </div>
    </div>
  </div>
</header>

// client/src/components/Header.tsx
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { Search, Bell, User, Menu, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function Header() {
  const [location] = useLocation();
  const [isSearchOpen, setIsSearchOpen] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  const navigation = [
    { name: "Home", href: "/" },
    { name: "Movies", href: "/movies" },
    { name: "TV Shows", href: "/tv-shows" },
    { name: "My List", href: "/my-list" },
  ];

  return (
    <header className="fixed top-0 left-0 right-0 z-50 bg-background/95 backdrop-blur-sm border-b border-border/40">
      <div className="container mx-auto px-4 py-3">
        <div className="flex items-center justify-between">
          {/* Logo */}
          <Link href="/" className="flex-shrink-0">
            <div className="text-2xl font-bold text-primary">WatchID</div>
          </Link>

          {/* Desktop Navigation */}
          <nav className="hidden md:flex items-center space-x-8">
            {navigation.map((item) => (
              <Link
                key={item.name}
                href={item.href}
                className={`text-sm font-medium transition-colors hover:text-foreground ${
                  location === item.href
                    ? "text-foreground"
                    : "text-muted-foreground"
                }`}
                data-testid={`nav-${item.name.toLowerCase()}`}
              >
                {item.name}
              </Link>
            ))}
          </nav>

          {/* Search and User Actions */}
          <div className="flex items-center space-x-3">
            {/* Search */}
            {isSearchOpen ? (
              <div className="flex items-center space-x-2">
                <Input
                  type="search"
                  placeholder="Search movies, shows..."
                  className="w-64"
                  data-testid="input-search"
                  onKeyDown={(e) => {
                    if (e.key === "Escape") setIsSearchOpen(false);
                  }}
                />
                <Button
                  size="icon"
                  variant="ghost"
                  onClick={() => setIsSearchOpen(false)}
                  data-testid="button-close-search"
                >
                  <X className="h-4 w-4" />
                </Button>
              </div>
            ) : (
              <Button
                size="icon"
                variant="ghost"
                onClick={() => setIsSearchOpen(true)}
                data-testid="button-search"
              >
                <Search className="h-4 w-4" />
              </Button>
            )}

            {/* Notifications */}
            <Button size="icon" variant="ghost" data-testid="button-notifications">
              <Bell className="h-4 w-4" />
            </Button>

            {/* User Profile */}
            <Button size="icon" variant="ghost" data-testid="button-profile">
              <User className="h-4 w-4" />
            </Button>

            {/* Mobile Menu Toggle */}
            <Button
              size="icon"
              variant="ghost"
              className="md:hidden"
              onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
              data-testid="button-mobile-menu"
            >
              {isMobileMenuOpen ? (
                <X className="h-4 w-4" />
              ) : (
                <Menu className="h-4 w-4" />
              )}
            </Button>
          </div>
        </div>

        {/* Mobile Navigation */}
        {isMobileMenuOpen && (
          <nav className="md:hidden mt-4 pb-4 border-t border-border/40">
            <div className="flex flex-col space-y-3 pt-4">
              {navigation.map((item) => (
                <Link
                  key={item.name}
                  href={item.href}
                  className={`text-sm font-medium py-2 px-3 rounded-md transition-colors ${
                    location === item.href
                      ? "bg-accent text-accent-foreground"
                      : "text-muted-foreground hover:text-foreground hover:bg-accent/50"
                  }`}
                  onClick={() => setIsMobileMenuOpen(false)}
                  data-testid={`nav-mobile-${item.name.toLowerCase()}`}
                >
                  {item.name}
                </Link>
              ))}
            </div>
          </nav>
        )}
      </div>
    </header>
  );
}
